"""
Django settings for llp project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x-d@sc%lw)-r_j+a)vp6ekn4^$pn9tqr_$qq60yx+m3kfa8)4o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.*.*', 'localhost', '127.0.0.1', '192.168.10.2', '192.168.10.3', 'mwin10', '192.168.1.3', '192.168.1.4', '192.168.3.29', 'sirius135.xyz', '192.168.2.8', '192.168.2.2',]


# Application definition

INSTALLED_APPS = [
    # local apps
    'lla1.apps.Lla1Config',
    'accounts.apps.AccountsConfig',
    #'accounts',
    # third party apps
    'django_bootstrap5',
    "debug_toolbar",
    # default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    
]

ROOT_URLCONF = 'llp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# my setting:redirect to lla1 after login
LOGIN_REDIRECT_URL = 'lla1:topics' # error if use  '/lla1/

LOGOUT_REDIRECT_URL = 'lla1:index'
LOGIN_URL = 'accounts:login'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# python manager.py collectfiles will use the root fold to save all static files, 
# and nginx will set the root fold as static fold to serve
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
# collectfiles will search below folds as well
STATICFILES_DIRS = [
    BASE_DIR / "static",  #os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = ['http://sirius135.xyz:81', 'https://sirius135.xyz:81']
CORS_ALLOWED_ORIGINS = [
    'http://sirius135.xyz:81',
]

# Add this line to specify the custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

ALIYUN_ACCESS_KEY_ID = 'LTAI5tMLZ9ag65u3bLeD9yPQ'

ALIYUN_SMS_SIGN_NAME = '阿里云短信测试'
ALIYUN_SMS_TEMPLATE_CODE = 'SMS_154950909'