# Generated by Django 4.2.16 on 2024-09-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lla1', '0005_mediaitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
