# Generated by Django 4.2.16 on 2024-09-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lla1', '0006_delete_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaItem',
            new_name='Media',
        ),
    ]
