# Generated by Django 4.2.16 on 2024-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lla1', '0008_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='change it', max_length=80),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
