# Generated by Django 4.2.16 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lla1', '0010_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
