# Generated by Django 4.2.16 on 2024-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lla1', '0012_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
